### ISSUE TITLE
Handling Old Tickets

### ISSUE THREAD

**Issue by ezfe** [Mojira/Arisa.bak#1]
If an issue hasn't been updated in a while and Affects Version/s doesn't contain the latest version, add a comment asking if the issue is still relevant.

If the issue isn't updated in a few months, the bot should resolve it automatically and add a comment.

**Comment by calebsander** [comment]
It would be useful if the resolving step didn't happen on confirmed issues.

**Comment by Tora-B** [comment]
If it's resolving as Awaiting Response, then why does it matter whether it's confirmed or not?

**Comment by ezfe** [comment]
Yeah, confirmed only indicates it happened for version X, and theoretically has no correlation to "still happening"

**Comment by calebsander** [comment]
I guess it doesn't really matter. If a mod confirms an issue, they don't necessarily start watching it, so this would allow tickets where the original user is no longer active to get marked as resolved.
