### ISSUE TITLE
Update pinned and linked fields

### ISSUE THREAD

**Issue by ezfe** [Mojira/Arisa.bak#2]
The bot should automatically update the values of the pinned and/or linked fields when an issue link is added, updated or removed.

**Comment by calebsander** [comment]
Do wrote a link not a long time ago, and it totally spammed the activity feed for days

**Comment by Synchunk** [comment]
While spam shouldn't be a huge problem (remember the flood when Arisa started removing redundant labels? That lasted for more than a week!), I guess you could add this feature as an `@updtd_module` so that it's only triggered on issues that are updated by someone.
