### ISSUE TITLE
Add New Versions To Parents

### ISSUE THREAD

**Issue by ezfe** [Mojira/Arisa.bak#3]
When a new version is added to an issue that's resolved as duplicate, the version should be added to the parent ticket as well.

**Comment by calebsander** [comment]
Also, when resolving as a duplicate, it would be useful for any new versions to get copied onto the original ticket

**Comment by ezfe** [comment]
I think that's the idea?

**Comment by calebsander** [comment]
I thought you meant when people add new versions later to their tickets which are duplicates

**Comment by ezfe** [comment]
In theory it should be the same behavior, but agreed
