### ISSUE TITLE
Disable Mod On Ticket

### ISSUE THREAD

**Issue by ezfe** [Mojira/Arisa.bak#7]
Some sort of comment tag (similar to MEQS system) that will cause the Bot to not modify the ticket.

**Comment by Synchunk** [comment]
I'd use the IssuePool for that. When it would normally add something to the `@issues` and `@updated_issues` variables, check the issue for that comment first and don't add it if one is found.
However, there are two problems with that:
* Users would be able to post such comments themselves, either by looking at existing comments (if they're public) or by reading the source code.
* It affects `@issue_modules`, `@crash_modules` and `@updtd_modules`, but not `@query_modules` as they run the queries themselves. One would have to add that check to every single `@query_module`. However, currently, there aren't many of them and they don't do anything important.

The best solution is a JIRA `customfield`, obviously.

**Comment by Mustek** [comment]
Use the confirmation status. Can only be adapted by mods.

**Comment by Tora-B** [comment]
Use confirmation status for what? Arisa does useful things on both confirmed and unconfirmed tickets, though I do think it shouldn't resolve issues that have been marked confirmed, or were just updated by a mod. It's annoying to reopen an issue, only for Arisa to come along and resolve it again.
